theme: jekyll-theme-architect
title: Dmitry Torshin Blog
email: dmitry.a.torshin@google.com
description: > Home blog of a Data Satanist
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://justm57.github.io" # the base hostname & protocol for your site
twitter_username: gotta_get_ya
github_username:  justm57

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
